import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from './Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="bg-blue-500 text-white">
          <Navbar />
        </header>
        <main className="container p-4 mx-auto">{children}</main>
        <footer className="bg-gray-200 text-gray-700">
          <div className="container p-4 mx-auto">{/* Footer content goes here */}</div>
        </footer>
      </body>
    </html>
  );
}
